/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'id' : bigint, 'items' : Array<CartItem> }
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export type CurrencyCents = bigint;
export interface Product {
  'id' : ProductId,
  'isOnSale' : boolean,
  'name' : string,
  'description' : string,
  'isFeatured' : boolean,
  'category' : string,
  'rating' : number,
  'price' : CurrencyCents,
  'reviewCount' : bigint,
}
export type ProductId = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], ProductId>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Cart>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getOnSaleProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'placeOrder' : ActorMethod<[], CurrencyCents>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];