/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const CurrencyCents = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'isOnSale' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : CurrencyCents,
  'reviewCount' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({ 'id' : IDL.Nat, 'items' : IDL.Vec(CartItem) });

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [ProductId], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOnSaleProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func([], [CurrencyCents], []),
  'removeFromCart' : IDL.Func([ProductId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const CurrencyCents = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'isOnSale' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : CurrencyCents,
    'reviewCount' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Cart = IDL.Record({ 'id' : IDL.Nat, 'items' : IDL.Vec(CartItem) });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [ProductId], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOnSaleProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeOrder' : IDL.Func([], [CurrencyCents], []),
    'removeFromCart' : IDL.Func([ProductId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };